# Generated by Django 3.2.6 on 2021-12-23 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_folder', models.TextField(blank=True)),
                ('product1', models.CharField(max_length=255)),
                ('product_Link1', models.URLField(max_length=225, null=True)),
                ('product2', models.CharField(max_length=255)),
                ('product_Link2', models.URLField(max_length=225, null=True)),
                ('product3', models.CharField(max_length=255)),
                ('product_Link3', models.URLField(max_length=225, null=True)),
                ('product4', models.CharField(max_length=255)),
                ('product_Link4', models.URLField(max_length=225, null=True)),
                ('useful_links1', models.CharField(max_length=255)),
                ('useful_links_link1', models.URLField(max_length=255, null=True)),
                ('useful_links2', models.CharField(max_length=255)),
                ('seful_links_link2', models.URLField(max_length=255, null=True)),
                ('useful_links3', models.CharField(max_length=255)),
                ('seful_links_link3', models.URLField(max_length=255, null=True)),
                ('useful_links4', models.CharField(max_length=255)),
                ('seful_links_link4', models.URLField(max_length=255, null=True)),
                ('contact1', models.CharField(max_length=255)),
                ('contact_link1', models.URLField(max_length=225, null=True)),
                ('contact2', models.CharField(max_length=255)),
                ('contact_link2', models.URLField(max_length=225, null=True)),
                ('contact3', models.CharField(max_length=255)),
                ('contact_link3', models.URLField(max_length=225, null=True)),
                ('contact4', models.CharField(max_length=255)),
                ('contact_link4', models.URLField(max_length=225, null=True)),
                ('instagram', models.URLField(max_length=255, null=True)),
                ('reddit', models.URLField(max_length=255)),
                ('facebook', models.URLField(max_length=255)),
                ('email', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='admin', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description_title', models.CharField(max_length=255, null=True)),
                ('title1', models.CharField(max_length=255, null=True)),
                ('img1', models.ImageField(null=True, upload_to='images/')),
                ('description1', models.TextField(blank=True)),
                ('title2', models.CharField(max_length=255, null=True)),
                ('img2', models.ImageField(null=True, upload_to='images/')),
                ('description2', models.TextField(blank=True)),
                ('title3', models.CharField(max_length=255, null=True)),
                ('img3', models.ImageField(null=True, upload_to='images/')),
                ('description3', models.TextField(blank=True)),
                ('title4', models.CharField(max_length=255, null=True)),
                ('img4', models.ImageField(null=True, upload_to='images/')),
                ('description4', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Shop.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
    ]
