# Generated by Django 3.2.6 on 2021-08-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_folder', models.TextField(blank=True)),
                ('product1', models.CharField(max_length=255)),
                ('product2', models.CharField(max_length=255)),
                ('product3', models.CharField(max_length=255)),
                ('product4', models.CharField(max_length=255)),
                ('useful_links1', models.CharField(max_length=255)),
                ('useful_links2', models.CharField(max_length=255)),
                ('useful_links3', models.CharField(max_length=255)),
                ('useful_links4', models.CharField(max_length=255)),
                ('contact1', models.CharField(max_length=255)),
                ('contact2', models.CharField(max_length=255)),
                ('contact3', models.CharField(max_length=255)),
                ('contact4', models.CharField(max_length=255)),
                ('instagrm', models.CharField(max_length=255)),
                ('reddit', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
