# Generated by Django 3.2.6 on 2021-08-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_bottomfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomfolder',
            name='instagrm',
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='instagram',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottomfolder',
            name='email',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bottomfolder',
            name='facebook',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bottomfolder',
            name='reddit',
            field=models.URLField(max_length=255),
        ),
    ]
