# Generated by Django 3.2.6 on 2021-08-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20210814_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomfolder',
            name='contact_link1',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='contact_link2',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='contact_link3',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='contact_link4',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='product_Link1',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='product_Link2',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='product_Link3',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='product_Link4',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='seful_links_link2',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='seful_links_link3',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='seful_links_link4',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottomfolder',
            name='useful_links_link1',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
