# Generated by Django 3.2.6 on 2022-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20220103_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_baner', models.ImageField(null=True, upload_to='images/')),
                ('titel_baner', models.CharField(max_length=255)),
                ('description_baner', models.TextField(blank=True)),
                ('link', models.URLField(max_length=225, null=True)),
            ],
        ),
    ]
