# Generated by Django 3.2.6 on 2022-01-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_baner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title3',
        ),
    ]
